// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `hub.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct HubFrame {
    // message fields
    pub frameType: ::std::string::String,
    pub timestamp: i64,
    pub image: ::std::vec::Vec<u8>,
    pub sequence: i64,
    pub camId: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a HubFrame {
    fn default() -> &'a HubFrame {
        <HubFrame as ::protobuf::Message>::default_instance()
    }
}

impl HubFrame {
    pub fn new() -> HubFrame {
        ::std::default::Default::default()
    }

    // string frameType = 1;


    pub fn get_frameType(&self) -> &str {
        &self.frameType
    }
    pub fn clear_frameType(&mut self) {
        self.frameType.clear();
    }

    // Param is passed by value, moved
    pub fn set_frameType(&mut self, v: ::std::string::String) {
        self.frameType = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_frameType(&mut self) -> &mut ::std::string::String {
        &mut self.frameType
    }

    // Take field
    pub fn take_frameType(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.frameType, ::std::string::String::new())
    }

    // int64 timestamp = 2;


    pub fn get_timestamp(&self) -> i64 {
        self.timestamp
    }
    pub fn clear_timestamp(&mut self) {
        self.timestamp = 0;
    }

    // Param is passed by value, moved
    pub fn set_timestamp(&mut self, v: i64) {
        self.timestamp = v;
    }

    // bytes image = 3;


    pub fn get_image(&self) -> &[u8] {
        &self.image
    }
    pub fn clear_image(&mut self) {
        self.image.clear();
    }

    // Param is passed by value, moved
    pub fn set_image(&mut self, v: ::std::vec::Vec<u8>) {
        self.image = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_image(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.image
    }

    // Take field
    pub fn take_image(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.image, ::std::vec::Vec::new())
    }

    // int64 sequence = 4;


    pub fn get_sequence(&self) -> i64 {
        self.sequence
    }
    pub fn clear_sequence(&mut self) {
        self.sequence = 0;
    }

    // Param is passed by value, moved
    pub fn set_sequence(&mut self, v: i64) {
        self.sequence = v;
    }

    // string camId = 5;


    pub fn get_camId(&self) -> &str {
        &self.camId
    }
    pub fn clear_camId(&mut self) {
        self.camId.clear();
    }

    // Param is passed by value, moved
    pub fn set_camId(&mut self, v: ::std::string::String) {
        self.camId = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_camId(&mut self) -> &mut ::std::string::String {
        &mut self.camId
    }

    // Take field
    pub fn take_camId(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.camId, ::std::string::String::new())
    }
}

impl ::protobuf::Message for HubFrame {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.frameType)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.timestamp = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.image)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.sequence = tmp;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.camId)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.frameType.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.frameType);
        }
        if self.timestamp != 0 {
            my_size += ::protobuf::rt::value_size(2, self.timestamp, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.image.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.image);
        }
        if self.sequence != 0 {
            my_size += ::protobuf::rt::value_size(4, self.sequence, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.camId.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.camId);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.frameType.is_empty() {
            os.write_string(1, &self.frameType)?;
        }
        if self.timestamp != 0 {
            os.write_int64(2, self.timestamp)?;
        }
        if !self.image.is_empty() {
            os.write_bytes(3, &self.image)?;
        }
        if self.sequence != 0 {
            os.write_int64(4, self.sequence)?;
        }
        if !self.camId.is_empty() {
            os.write_string(5, &self.camId)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> HubFrame {
        HubFrame::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "frameType",
                |m: &HubFrame| { &m.frameType },
                |m: &mut HubFrame| { &mut m.frameType },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "timestamp",
                |m: &HubFrame| { &m.timestamp },
                |m: &mut HubFrame| { &mut m.timestamp },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "image",
                |m: &HubFrame| { &m.image },
                |m: &mut HubFrame| { &mut m.image },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "sequence",
                |m: &HubFrame| { &m.sequence },
                |m: &mut HubFrame| { &mut m.sequence },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "camId",
                |m: &HubFrame| { &m.camId },
                |m: &mut HubFrame| { &mut m.camId },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<HubFrame>(
                "HubFrame",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static HubFrame {
        static instance: ::protobuf::rt::LazyV2<HubFrame> = ::protobuf::rt::LazyV2::INIT;
        instance.get(HubFrame::new)
    }
}

impl ::protobuf::Clear for HubFrame {
    fn clear(&mut self) {
        self.frameType.clear();
        self.timestamp = 0;
        self.image.clear();
        self.sequence = 0;
        self.camId.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for HubFrame {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for HubFrame {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\thub.proto\"\x9a\x01\n\x08HubFrame\x12\x1e\n\tframeType\x18\x01\x20\
    \x01(\tR\tframeTypeB\0\x12\x1e\n\ttimestamp\x18\x02\x20\x01(\x03R\ttimes\
    tampB\0\x12\x16\n\x05image\x18\x03\x20\x01(\x0cR\x05imageB\0\x12\x1c\n\
    \x08sequence\x18\x04\x20\x01(\x03R\x08sequenceB\0\x12\x16\n\x05camId\x18\
    \x05\x20\x01(\tR\x05camIdB\0:\0B\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
